# Generated by Django 3.2.25 on 2025-08-28 08:20

from django.db import migrations, models
import jsonfield.fields
import problem.models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_problem_share_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='io_mode',
            field=jsonfield.fields.JSONField(default=problem.models._default_io_mode),
        ),
        migrations.AlterField(
            model_name='problem',
            name='languages',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='samples',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statistic_info',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='problem',
            name='template',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_case_score',
            field=jsonfield.fields.JSONField(),
        ),
    ]
