# Generated by Django 4.2.23 on 2025-08-28 13:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('plugin_version', models.CharField(default='1.0.0', max_length=20, verbose_name='插件版本')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('question_count', models.IntegerField(default=0, verbose_name='题目数量')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='choice_question.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '选择题分类',
                'verbose_name_plural': '选择题分类',
                'db_table': 'choice_plugin_category',
                'ordering': ['tree_id', 'lft'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('plugin_version', models.CharField(default='1.0.0', max_length=20, verbose_name='插件版本')),
                ('name', models.CharField(help_text='标签名称，不能重复', max_length=50, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(default='#409EFF', help_text='标签显示颜色，格式为 #RRGGBB', max_length=7, validators=[django.core.validators.RegexValidator(message='颜色格式必须为 #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='标签颜色')),
                ('description', models.TextField(blank=True, help_text='标签的详细描述', verbose_name='标签描述')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用此标签', verbose_name='是否启用')),
                ('question_count', models.IntegerField(default=0, help_text='使用此标签的题目数量', verbose_name='关联题目数量')),
                ('tag_type', models.CharField(choices=[('difficulty', '难度标签'), ('subject', '学科标签'), ('knowledge', '知识点标签'), ('custom', '自定义标签')], default='custom', max_length=20, verbose_name='标签类型')),
            ],
            options={
                'verbose_name': '选择题标签',
                'verbose_name_plural': '选择题标签',
                'db_table': 'choice_plugin_tag',
                'ordering': ['tag_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('plugin_version', models.CharField(default='1.0.0', max_length=20, verbose_name='插件版本')),
                ('_id', models.CharField(db_index=True, help_text='题目的显示ID，用于前端展示', max_length=32, verbose_name='显示ID')),
                ('title', models.TextField(help_text='题目的标题或问题描述', verbose_name='题目标题')),
                ('description', utils.models.RichTextField(help_text='题目的详细描述，支持富文本格式', verbose_name='题目描述')),
                ('question_type', models.CharField(choices=[('single', '单选题'), ('multiple', '多选题')], max_length=10, verbose_name='题目类型')),
                ('options', models.JSONField(help_text='格式: [{"key": "A", "text": "选项内容"}, ...]', verbose_name='选项列表')),
                ('correct_answer', models.CharField(help_text='单选题格式: A，多选题格式: A,B,C', max_length=10, verbose_name='正确答案')),
                ('explanation', utils.models.RichTextField(blank=True, help_text='题目答案的详细解析', verbose_name='答案解析')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='medium', max_length=10, verbose_name='难度等级')),
                ('score', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='题目分值')),
                ('total_submit', models.IntegerField(default=0, verbose_name='总提交次数')),
                ('total_accepted', models.IntegerField(default=0, verbose_name='正确提交次数')),
                ('visible', models.BooleanField(default=True, verbose_name='是否可见')),
                ('is_public', models.BooleanField(default=True, help_text='是否对所有用户公开', verbose_name='是否公开')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='choice_question.category', verbose_name='所属分类')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_choice_questions', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('tags', models.ManyToManyField(blank=True, to='choice_question.questiontag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '选择题',
                'verbose_name_plural': '选择题',
                'db_table': 'choice_plugin_question',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='WrongQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('plugin_version', models.CharField(default='1.0.0', max_length=20, verbose_name='插件版本')),
                ('wrong_count', models.IntegerField(default=1, help_text='用户答错此题的总次数', validators=[django.core.validators.MinValueValidator(1)], verbose_name='错误次数')),
                ('last_wrong_time', models.DateTimeField(auto_now=True, verbose_name='最后错误时间')),
                ('first_wrong_time', models.DateTimeField(auto_now_add=True, verbose_name='首次错误时间')),
                ('note', models.TextField(blank=True, help_text='用户对此错题的个人笔记', verbose_name='用户笔记')),
                ('is_mastered', models.BooleanField(default=False, help_text='用户是否已经掌握此题', verbose_name='是否已掌握')),
                ('mastered_time', models.DateTimeField(blank=True, null=True, verbose_name='掌握时间')),
                ('error_type', models.CharField(choices=[('careless', '粗心错误'), ('knowledge', '知识点不熟'), ('comprehension', '理解错误'), ('calculation', '计算错误'), ('other', '其他')], default='other', max_length=20, verbose_name='错误类型')),
                ('last_wrong_answer', models.CharField(blank=True, max_length=10, verbose_name='最后错误答案')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choice_question.choicequestion', verbose_name='错题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '错题记录',
                'verbose_name_plural': '错题记录',
                'db_table': 'choice_plugin_wrong_question',
                'ordering': ['-last_wrong_time'],
                'indexes': [models.Index(fields=['user', 'is_mastered'], name='choice_plug_user_id_bec929_idx'), models.Index(fields=['question', 'wrong_count'], name='choice_plug_questio_ae8106_idx')],
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='ChoiceQuestionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('plugin_version', models.CharField(default='1.0.0', max_length=20, verbose_name='插件版本')),
                ('selected_answer', models.CharField(help_text='单选题格式: A，多选题格式: A,B,C', max_length=10, verbose_name='用户选择的答案')),
                ('is_correct', models.BooleanField(verbose_name='是否正确')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='得分')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('time_spent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='答题用时（秒）')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choice_question.choicequestion', verbose_name='关联题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交用户')),
            ],
            options={
                'verbose_name': '选择题提交记录',
                'verbose_name_plural': '选择题提交记录',
                'db_table': 'choice_plugin_submission',
                'ordering': ['-submit_time'],
                'indexes': [models.Index(fields=['user', 'question'], name='choice_plug_user_id_c6bc2b_idx'), models.Index(fields=['question', 'is_correct'], name='choice_plug_questio_46ea81_idx'), models.Index(fields=['submit_time'], name='choice_plug_submit__b4c0e3_idx')],
            },
        ),
    ]
