# Generated by Django 4.2.23 on 2025-09-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice_question', '0002_exampaper_examsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='language',
            field=models.CharField(blank=True, choices=[('cpp', 'C++'), ('c', 'C'), ('java', 'Java'), ('python', 'Python'), ('javascript', 'JavaScript'), ('go', 'Go'), ('rust', 'Rust'), ('php', 'PHP'), ('csharp', 'C#'), ('ruby', 'Ruby'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('typescript', 'TypeScript'), ('scala', 'Scala'), ('perl', 'Perl'), ('r', 'R'), ('matlab', 'MATLAB')], help_text='题目涉及的编程语言，用于代码高亮', max_length=20, null=True, verbose_name='编程语言'),
        ),
    ]
