# Generated by Django 4.2.23 on 2025-09-04 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choice_question', '0004_choicequestion_import_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='paper_type',
            field=models.CharField(choices=[('dynamic', '动态生成'), ('fixed', '固定题目')], default='dynamic', help_text='动态生成：根据配置随机生成题目；固定题目：使用导入的固定题目集合', max_length=20, verbose_name='试卷类型'),
        ),
        migrations.CreateModel(
            name='ExamPaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('plugin_version', models.CharField(default='1.0.0', max_length=20, verbose_name='插件版本')),
                ('order', models.IntegerField(verbose_name='题目顺序')),
                ('score', models.IntegerField(default=2, verbose_name='题目分值')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='choice_question.exampaper', verbose_name='试卷')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choice_question.choicequestion', verbose_name='题目')),
            ],
            options={
                'verbose_name': '试卷题目',
                'verbose_name_plural': '试卷题目',
                'db_table': 'choice_exam_paper_question',
                'ordering': ['order'],
                'unique_together': {('paper', 'order'), ('paper', 'question')},
            },
        ),
    ]
