# Generated by Django 4.2.23 on 2025-08-30 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('choice_question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('category', '分类练习'), ('tag', '标签练习'), ('random', '随机练习'), ('wrong', '错题练习'), ('favorite', '收藏练习'), ('difficulty', '难度练习')], max_length=20, verbose_name='练习模式')),
                ('name', models.CharField(max_length=100, verbose_name='模式名称')),
                ('description', models.TextField(blank=True, verbose_name='模式描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '练习模式',
                'verbose_name_plural': '练习模式',
                'db_table': 'choice_practice_mode',
            },
        ),
        migrations.CreateModel(
            name='PracticeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.IntegerField(default=0, verbose_name='总练习次数')),
                ('total_questions', models.IntegerField(default=0, verbose_name='总答题数')),
                ('total_correct', models.IntegerField(default=0, verbose_name='总正确数')),
                ('total_time_spent', models.IntegerField(default=0, verbose_name='总用时(秒)')),
                ('category_stats', models.JSONField(default=dict, verbose_name='分类统计')),
                ('difficulty_stats', models.JSONField(default=dict, verbose_name='难度统计')),
                ('tag_stats', models.JSONField(default=dict, verbose_name='标签统计')),
                ('daily_stats', models.JSONField(default=dict, verbose_name='每日统计')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '练习统计',
                'verbose_name_plural': '练习统计',
                'db_table': 'choice_practice_statistics',
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='练习标题')),
                ('status', models.CharField(choices=[('active', '进行中'), ('paused', '暂停'), ('completed', '已完成'), ('abandoned', '已放弃')], default='active', max_length=20, verbose_name='状态')),
                ('settings', models.JSONField(default=dict, verbose_name='练习设置')),
                ('total_questions', models.IntegerField(default=0, verbose_name='总题数')),
                ('answered_questions', models.IntegerField(default=0, verbose_name='已答题数')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='正确答案数')),
                ('total_score', models.IntegerField(default=0, verbose_name='总分')),
                ('current_score', models.IntegerField(default=0, verbose_name='当前得分')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('total_time_spent', models.IntegerField(default=0, verbose_name='总用时(秒)')),
                ('current_question_index', models.IntegerField(default=0, verbose_name='当前题目索引')),
                ('question_order', models.JSONField(default=list, verbose_name='题目顺序')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choice_practice.practicemode', verbose_name='练习模式')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '练习会话',
                'verbose_name_plural': '练习会话',
                'db_table': 'choice_practice_session',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='PracticeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=10, verbose_name='选择的答案')),
                ('is_correct', models.BooleanField(verbose_name='是否正确')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('time_spent', models.IntegerField(default=0, verbose_name='用时(秒)')),
                ('answer_time', models.DateTimeField(auto_now_add=True, verbose_name='答题时间')),
                ('question_index', models.IntegerField(verbose_name='题目序号')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='用户代理')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choice_question.choicequestion', verbose_name='题目')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choice_practice.practicesession', verbose_name='练习会话')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '练习记录',
                'verbose_name_plural': '练习记录',
                'db_table': 'choice_practice_record',
                'ordering': ['-answer_time'],
                'unique_together': {('session', 'question')},
            },
        ),
    ]
