# Generated by Django 2.1.7 on 2025-09-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_fix_jsonfield_sqlite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_keys',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='acm_problems_status',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='oi_problems_status',
            field=models.TextField(default='{}'),
        ),
    ]
