# Generated by Django 2.1.7 on 2025-09-08 05:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0013_auto_20250828_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='submission',
            name='statistic_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
