# Generated by Django 2.1.7 on 2025-09-08 05:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import problem.models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0015_auto_20250828_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='io_mode',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=problem.models._default_io_mode),
        ),
        migrations.AlterField(
            model_name='problem',
            name='languages',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='samples',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statistic_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='problem',
            name='template',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_case_score',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
