# Generated by Django 4.2.24 on 2025-09-18 03:52

from django.db import migrations, models
import problem.models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0016_auto_20250908_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='io_mode',
            field=models.JSONField(default=problem.models._default_io_mode),
        ),
        migrations.AlterField(
            model_name='problem',
            name='languages',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='samples',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statistic_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='problem',
            name='template',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_case_score',
            field=models.JSONField(),
        ),
    ]
