# Generated by Django 2.1.7 on 2025-09-08 00:37

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_is_active_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_keys',
            field=jsonfield.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='acm_problems_status',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='oi_problems_status',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
