# Generated by Django 2.1.7 on 2025-09-08 00:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_fix_session_keys_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_keys',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='acm_problems_status',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='oi_problems_status',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
