# Generated by Django 2.1.7 on 2025-09-08 05:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_auto_20250828_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmcontestrank',
            name='submission_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='contest',
            name='allowed_ip_ranges',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='oicontestrank',
            name='submission_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
