# Generated by Django 3.2.25 on 2025-08-28 08:20

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0003_migrate_languages_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysoptions',
            name='value',
            field=jsonfield.fields.JSONField(),
        ),
    ]
