# Generated by Django 4.2.23 on 2025-09-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice_question', '0003_choicequestion_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='import_order',
            field=models.IntegerField(default=0, help_text='题目导入时的顺序，用于考试模式按导入顺序显示题目', verbose_name='导入顺序'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='use_import_order',
            field=models.BooleanField(default=False, help_text='是否按题目导入顺序显示题目，适用于整套试卷导入的场景', verbose_name='按导入顺序排序'),
        ),
    ]
