# Generated by Django 2.1.7 on 2025-09-08 05:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice_question', '0006_topic_topicpracticerecord_topiccategoryrelation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='格式: [{"key": "A", "text": "选项内容"}, ...]', verbose_name='选项列表'),
        ),
        migrations.AlterField(
            model_name='choicequestionsubmission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='difficulty_distribution',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text="格式: {'easy': 5, 'medium': 3, 'hard': 2}", verbose_name='难度分布'),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exampaperquestion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='答案记录'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='questions',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='存储题目ID列表', verbose_name='题目列表'),
        ),
        migrations.AlterField(
            model_name='questiontag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topiccategoryrelation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topicpracticerecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topicquestion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topictagrelation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topicwrongquestionrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wrongquestion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
