# Generated by Django 4.2.24 on 2025-09-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0014_auto_20250908_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='submission',
            name='statistic_info',
            field=models.JSONField(default=dict),
        ),
    ]
