# Generated by Django 2.1.7 on 2025-09-08 05:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_alter_sysoptions_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysoptions',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
