# Generated by Django 4.2.24 on 2025-09-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0005_auto_20250908_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysoptions',
            name='value',
            field=models.JSONField(),
        ),
    ]
